version: "2.1"
services:
  webtop:
    image: ghcr.io/linuxserver/webtop
    container_name: webtop
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - .appdata/webtop:/config
    ports:
      - 3000:3000
    restart: unless-stopped
